spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: order_user
    password: secret_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: inventory-service

  boot:
    admin:
      client:
        url: http://admin-server:9090
        auto-registration: true
        instance:
          prefer-ip: true
        connection-timeout: 5s
        read-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

  health:
    defaults:
      enabled: true
    probes:
      enabled: true

server:
  port: 8080
